# Generated by Django 5.0 on 2023-12-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_wish_rename_birthdate_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techname', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secret_santa.wishstatus'),
        ),
    ]
